/* guiUnnamed */
local guiUnnamed = {};
guiUnnamed.window <- GUIWindow();
guiUnnamed.window.setText("GUIWindow");
guiUnnamed.window.setVisible(false);
guiUnnamed.window.setSize(400.0, 400.0, false);
guiUnnamed.window.setPosition(262.0, 137.0, false);
guiUnnamed.object <- array(10, null);
guiUnnamed.object[1] = GUIButton();
guiUnnamed.object[1].setText("<");
guiUnnamed.object[1].setParent(guiUnnamed.window.getName());
guiUnnamed.object[1].setVisible(true);
guiUnnamed.object[1].setSize(25.0, 25.0, false);
guiUnnamed.object[1].setPosition(6.0, 17.0, false);
guiUnnamed.object[2] = GUIButton();
guiUnnamed.object[2].setText(">");
guiUnnamed.object[2].setParent(guiUnnamed.window.getName());
guiUnnamed.object[2].setVisible(true);
guiUnnamed.object[2].setSize(25.0, 25.0, false);
guiUnnamed.object[2].setPosition(363.0, 16.0, false);
guiUnnamed.object[3] = GUIImage("Новый точечный рисунок.bmp");
guiUnnamed.object[3].setParent(guiUnnamed.window.getName());
guiUnnamed.object[3].setVisible(true);
guiUnnamed.object[3].setSize(250.0, 150.0, false);
guiUnnamed.object[3].setPosition(71.0, 17.0, false);
guiUnnamed.object[4] = GUIEditBox();
guiUnnamed.object[4].setText("Цвет 1");
guiUnnamed.object[4].setParent(guiUnnamed.window.getName());
guiUnnamed.object[4].setVisible(true);
guiUnnamed.object[4].setSize(90.0, 21.0, false);
guiUnnamed.object[4].setPosition(70.0, 178.0, false);
guiUnnamed.object[5] = GUIEditBox();
guiUnnamed.object[5].setText("Цвет 2");
guiUnnamed.object[5].setParent(guiUnnamed.window.getName());
guiUnnamed.object[5].setVisible(true);
guiUnnamed.object[5].setSize(90.0, 21.0, false);
guiUnnamed.object[5].setPosition(230.0, 177.0, false);
guiUnnamed.object[6] = GUIEditBox();
guiUnnamed.object[6].setText("Цвет 3");
guiUnnamed.object[6].setParent(guiUnnamed.window.getName());
guiUnnamed.object[6].setVisible(true);
guiUnnamed.object[6].setSize(90.0, 21.0, false);
guiUnnamed.object[6].setPosition(70.0, 206.0, false);
guiUnnamed.object[7] = GUIEditBox();
guiUnnamed.object[7].setText("Цвет 4");
guiUnnamed.object[7].setParent(guiUnnamed.window.getName());
guiUnnamed.object[7].setVisible(true);
guiUnnamed.object[7].setSize(90.0, 21.0, false);
guiUnnamed.object[7].setPosition(230.0, 205.0, false);
guiUnnamed.object[8] = GUIImage("Новый точечный рисунок.bmp");
guiUnnamed.object[8].setParent(guiUnnamed.window.getName());
guiUnnamed.object[8].setVisible(true);
guiUnnamed.object[8].setSize(250.0, 100.0, false);
guiUnnamed.object[8].setPosition(69.0, 234.0, false);
guiUnnamed.object[9] = GUIButton();
guiUnnamed.object[9].setText("OK");
guiUnnamed.object[9].setParent(guiUnnamed.window.getName());
guiUnnamed.object[9].setVisible(true);
guiUnnamed.object[9].setSize(90.0, 28.0, false);
guiUnnamed.object[9].setPosition(69.0, 340.0, false);
guiUnnamed.object[10] = GUIButton();
guiUnnamed.object[10].setText("Cancel");
guiUnnamed.object[10].setParent(guiUnnamed.window.getName());
guiUnnamed.object[10].setVisible(true);
guiUnnamed.object[10].setSize(90.0, 28.0, false);
guiUnnamed.object[10].setPosition(227.0, 340.0, false);
/* API: */
guiUnnamed.visible <- false;
guiUnnamed.toggle <- function() { guiUnnamed.visible = !guiUnnamed.visible; guiUnnamed.window.setVisible(guiUnnamed.visible); guiToggleCursor(guiUnnamed.visible); }
guiUnnamed.allowClose <- true;
guiUnnamed.onWindowClose <- function(wndName, wndState) { if(wndName!= guiUnnamed.window.getName()) return; else if(guiUnnamed.allowClose && guiUnnamed.visible) guiUnnamed.toggle(); }
guiUnnamed.onButtonClick <- function(btnName, btnState){if(!guiUnnamed.visible)return;else try {foreach(elemid, elem in guiUnnamed.object){if (elem.getName() == btnName)return onGuiClickButton(guiUnnamed, elemid);} } catch(e) { } }
addEvent("buttonClick", guiUnnamed.onButtonClick);
addEvent("windowClose", guiUnnamed.onWindowClose);
